src/contacts/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    ContactCreateView,
    ContactDetailView,
    ContactDeleteView,
    ContactUpdateView,
    ContactListView,
)

# from pages.views import home_view, about_view, contact_view
# from contacts.views import (
#     contact_create_view,
#     contact_list_view,
#     contact_detail_view,
#     contact_update_view,
#     contact_delete_view,
# )

app_name = "contacts"

urlpatterns = [
    path("", ContactListView.as_view(), name="contact-list"),
    path("<int:id>/", ContactDetailView.as_view(), name="contact-detail"),
    path("create/", ContactCreateView.as_view(), name="contact-create"),
    path("<int:id>/update/", ContactUpdateView.as_view(), name="contact-update"),
    path("<int:id>/delete/", ContactDeleteView.as_view(), name="contact-delete"),
]

# urlpatterns = [
#     path("", contact_list_view, name="contact-list"),
#     path("create/", contact_create_view, name="contact-create"),
#     path(
#         "detail/<int:id>", contact_detail_view, name="contact-detail"
#     ),  # id bhi argument me pass karni padegi``
#     path("update/<int:id>", contact_update_view, name="contact-update"),
#     path("delete/<int:id>", contact_delete_view, name="delete-contact"),
# ]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, about_view, contact_view

# from contacts.views import contact_create_view, contact_list_view, contact_detail_view


urlpatterns = [
    path("", include("contacts.urls")),
    path("admin/", admin.site.urls),
    path("home/", home_view, name="home"),
    path("about/", about_view, name="about-view"),
    path("contact/", contact_view, name="contact-view"),
]

src/contacts/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=20)
    # email = models.EmailField(max_length=50)
    # number = models.IntegerField(max_length=10)
    number = models.CharField(max_length=10)
    message = models.TextField(default="this is contact's personal number.")

    def get_absolute_url(self):
        # return f"/contacts/{self.id}"
        return reverse("contacts:contact-detail", kwargs={"id": self.id})

src/pages/models.py
from django.db import models

# Create your models here.

src/contacts/views.py
# from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .models import Contact
from .form import ContactForm

# # Create your views here.

from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)


class ContactCreateView(CreateView):
    template_name = "contacts/contact_create.html"
    form_class = ContactForm
    queryset = Contact.objects.all()

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class ContactListView(ListView):
    template_name = "contacts/contact_list.html"
    # queryset = Contact.objects.all()

    def get_queryset(self):
        search = self.request.GET.get("search")
        if search:
            contacts = Contact.objects.filter(name__startswith=search)
        else:
            contacts = Contact.objects.all()
        return contacts


class ContactDetailView(DetailView):
    template_name = "contacts/contact_detail.html"

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Contact, id=id_)


class ContactUpdateView(UpdateView):
    template_name = "contacts/contact_create.html"
    form_class = ContactForm
    queryset = Contact.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Contact, id=id_)

    def form_valid(self, form):
        print(form.cleand_data)
        return super().form_valid(form)


class ContactDeleteView(DeleteView):
    template_name = "contacts/contact_delete.html"

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Contact, id=id_)

    def get_success_url(self):
        return reverse("contacts:contact-list")


# def contact_create_view(request):
#     if request.method == "GET":
#         form = ContactForm()
#         context = {"form": form}
#     else:
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#         else:
#             context = {"form": form}
#             return render(request, "contacts/contact_create.html", context)
#         context = {"form": ContactForm()}
#         return redirect(
#             reverse("contacts:contact-list")
#         )  # is line se contact save karne par list view
#     return render(request, "contacts/contact_create.html", context)


# def contact_list_view(request):
#     search = request.GET.get("search")
#     if search:
#         contacts = Contact.objects.filter(name__startswith=search)
#     else:
#         contacts = Contact.objects.all()
#     context = {"contacts": contacts}
#     return render(request, "contacts/contact_list.html", context)


# def contact_detail_view(request, id):
#     obj = get_object_or_404(Contact, id=id)
#     context = {"object": obj}
#     return render(request, "contacts/contact_detail.html", context)

#     # obj = Contact.objects.get(id=id)
#     # context = {"name": obj.name, "message": obj.message, "number": obj.number}


# def contact_update_view(request, id):
#     obj = get_object_or_404(Contact, id=id)
#     if request.method == "GET":
#         form = ContactForm(instance=obj)
#         context = {
#             "form": form,
#             "id": obj.id,
#         }
#         return render(request, "contacts/contact_update.html", context)
#     else:
#         form = ContactForm(request.POST, instance=obj)
#         if form.is_valid():
#             form.save()
#         return redirect(reverse("contacts:contact-detail", kwargs={"id": obj.id}))


# def contact_delete_view(request, id):
#     obj = get_object_or_404(Contact, id=id)
#     if request.method == "POST":
#         print("post method")
#         obj.delete()
#         return redirect(reverse("contacts:contact-list"))
#     else:
#         print("get method")
#         context = {"obj": obj}
#         return render(request, "contacts/contact_delete.html", context)

src/pages/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def home_view(request, *args, **kwargs):
    return render(request, "home.html", {})


def about_view(request, *args, **kwargs):
    return render(request, "about.html", {})


def contact_view(request, *args, **kwargs):
    return render(request, "contacts.html", {})

src/contacts/templates/contacts/contact_create.html
{% block content %}

<form action="{% url 'contacts:contact-create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }} <br>
    <input type="submit" value="save">

    <!-- <button>save</button> -->
</form>

<button><a href="{% url 'contacts:contact-list' %}">Back to list</a></button>

<!-- {% endblock %}

{{ obj.id }} -->

<!-- {{ obj.id }} -->

src/contacts/templates/contacts/contact_delete.html
{% block content %}

<!-- <form action="." method="POST"> -->
<form action="." method="POST">
    {% csrf_token %}
    <h1>Do you want to delete this contact "{{ contact.name }}" ?</h1>
    <!-- <input type="submit" value="Submit"> -->
    <p><input type="submit" value="Yes"> <br><br><a href="../">Cancel</a></p>
</form>

{% endblock %}

src/contacts/templates/contacts/contact_detail.html
{% block content %}

<h1>{{ object.name }}</h1>
<p>{% if object.message != None %} {{ object.message }}{% else %} oh here we again. {% endif %} </p>
<p>{{ object.number }}</p>

<button><a href="{% url 'contacts:contact-update' object.id %}">Edit</a></button><br><br>
<button><a href="{% url 'contacts:contact-delete' object.id %}">Delete</a></button><br><br>
<button><a href="{% url 'contacts:contact-list' %}">Home</a></button>

<!-- <input type="submit" value="Edit">
<input type="button" value="Delete">
<button>delete</button> -->
<!-- <input type="submit" value="detail" name="detail" id="obj.id">  -->


{% endblock %}

src/contacts/templates/contacts/contact_list.html
{% block content %}
<h1>contacts list </h1>

<input type="text" id="search_input" placeholder="Type to search">
<button type="submit" onclick="search_contact()">Search</button>

<!-- ye contacts context se aaya hai jis par for loop chla hai -->
{% for instance in object_list %}
<!-- class base me context nhi lete to ye object_list lete hai. -->

<p> {{forloop.counter}} - <a href="{{ instance.get_absolute_url }}"> {{ instance.name }} </a></p>

{% endfor %}

<button><a href="{% url 'contacts:contact-create' %}">Create Contact</a></button>
<!-- <button><a href="{% url 'contacts:contact-list' %}">Back to list</a></button> -->

<script type="text/javascript">
    function search_contact() {
        var start_url = "{% url 'contacts:contact-list' %}"
        var search_input = document.getElementById('search_input').value;
        var final_url = start_url + "?search=" + search_input;
        window.location = final_url;
    } 
</script>

{% endblock %}

src/contacts/templates/contacts/contact_update.html
{% block content %}

<form action="{% url 'contacts:contact-update' id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }} <br>
    <input type="submit" value="save">

</form>
<button><a href="{% url 'contacts:contact-list' %}">Don't Save</a></button>

{% endblock %}

<!-- {{ obj.id }} -->

<!-- {{ obj.id }} -->

src/pages/templates/about.html
{% block content %}

<h1>hello from about view</h1>
<p>here we see the about page</p>


{% endblock %}

src/pages/templates/contacts.html
{% block content %}

<h1>CONTACTS</h1>
<p>this is contact's view</p>


{% endblock %}

src/pages/templates/home.html
{% block content %}

<h1>Hello world from home view</h1>
<p>this is templates about home view template.</p>

{% endblock %}